server:
  port: 9000
spring:
  application:
    name: netdisk-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.121.130:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user
          predicates:
            - Path=/user/**
          uri: lb://netdisk-user
        - id: file
          predicates:
            - Path=/file/**
          uri: lb://netdisk-file
        - id: share
          predicates:
            - Path=/share/**
          uri: lb://netdisk-file